postgresql:
  image: postgres:9.6
  ports:
    - 0.0.0.0:5432:5432
  environment:
    - POSTGRES_PASSWORD=mysecretpassword
  # volumes:
  #  - ./volumes/var/lib/postgresql/data:/var/lib/postgresql/data
