### Extends image from soapui-mockservice-runner
FROM fbascheper/soapui-mockservice-runner

### File Author / Maintainer
MAINTAINER "Diego Perez dperez@tcpsi.es"

### Open Ports
EXPOSE 8080

### Copy soap xml custom project
ADD soap-project /home/soapui/soapui-prj/
