version: '3.5'

services:
  nginx-env-vars:
    image: nginx:1.19
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80