version: "2"

services:
  myapp-sonarqube:
    image: sonarqube:7.1
    container_name: myapp-sonarqube
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://myapp-sonarqube-psql:5432/sonar
    volumes:
      - myapp_sonarqube_conf:/opt/sonarqube/conf
      - myapp_sonarqube_data:/opt/sonarqube/data
      - myapp_sonarqube_extensions:/opt/sonarqube/extensions
      - myapp_sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  myapp-sonarqube-psql:
    image: postgres
    container_name: myapp-sonarqube-psql
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - myapp_sonarqube_postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - myapp_sonarqube_postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge

volumes:
  myapp_sonarqube_conf:
  myapp_sonarqube_data:
  myapp_sonarqube_extensions:
  myapp_sonarqube_bundled-plugins:
  myapp_sonarqube_postgresql:
  myapp_sonarqube_postgresql_data:
