version: '3.5'

services:
  nginx-env-vars:
    image: nginx:1.16
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8080:80"
    command:
      - bash
      - -c
      - |
        cp /etc/nginx/templates/nginx-default.conf.template /etc/nginx/conf.d/default.conf
        sed -i -e 's/<<API_HOST>>/${API_HOST}/' -e 's/<<API_PORT>>/${API_PORT}/' /etc/nginx/conf.d/default.conf
      
        cat /etc/nginx/conf.d/default.conf
        nginx -g 'daemon off;'
        