version: '3.1'

services:

  holamundocert-nginx:
    image: nginx:latest
    ports:
      - 0.0.0.0:443:443
    volumes:
        - ./docker-conf:/etc/nginx/conf.d
        - ./dist:/usr/share/nginx/html
        - ./certificates:/etc/nginx/certificates
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
