mysql:
  image: mysql:latest
  ports:
    - 0.0.0.0:3306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=mysecretpassword
  volumes:
#    - ./volumes/mysql/var/lib/mysql:/var/lib/mysql
#    - ./volumes/mysql/var/log:/var/log
